### ISSUE TITLE
SS VAE

### ISSUE THREAD

**Issue by bmazoure** [probtorch/probtorch#21]
I noticed that the example does not explicitly use a classifier like mentioned in Kingma et al. 2014 to predict the labels, is that right?

**Comment by jwvdm** [comment]
It actually does. The objective functions `objectives.montecarlo.elbo` and `objective.importance.elbo` both incorporate the classification term with default strength `alpha=0.1`. The objective is `montecarlo` is the one that is defined in the paper.
