### ISSUE TITLE
NameErrors due to update

### ISSUE THREAD

**Issue by ttaa9** [probtorch/probtorch#36]
Perhaps I'm doing something wrong, but upon updating probtorch I began receiving errors like

`NameError: name 'sample_dim' is not defined`

I tracked down the errors and fixed them manually in the `site-packages` folder. The ones I found are

 * In `probtorch/util.py`, in the `batch_sum` function, the variables `sample_dim` and `batch_dim` are not defined (they have been changed to `sample_dims` and `batch_dims`).

 * In `probtorch/stochastic.py`, in the `log_batch_marginal` function, the input argument `sample_dims` is referred to as `sample_dim`.

**Comment by jwvdm** [comment]
@esennesh: Could you take a look at this?

**Comment by esennesh** [comment]
On it.

**Comment by esennesh** [comment]
https://github.com/probtorch/probtorch/pull/38

**Comment by esennesh** [comment]
@alicanb as you requested https://github.com/probtorch/probtorch/pull/39
